# Switches ----------------------------------------------
#
# Trigger when the switch is turning on.
# bindl = , switch:on:[switch name], exec, hyprctl keyword monitor "eDP-1, disable"
bindld = , switch:on:Lid Switch, Close Lid, exec, hyprctl keyword monitor "eDP-1, disable"
# Trigger when the switch is turning off.
# bindl = , switch:off:[switch name], exec, hyprctl keyword monitor "eDP-1, 2560x1600, 0x0, 1"
bindld = , switch:off:Lid Switch, Open Lid, exec, hyprctl keyword monitor "eDP-1, prefered, 1366x768@60, auto, 1"



# Bindings
#
# remove bindig for docker and asing it for disable laptor monitor
unbind = SUPER SHIFT, D
bindd = SUPER SHIFT, D, Disable laptop monitor, exec, hyprctl keyword monitor eDP-1, disable
bindd = SUPER SHIFT ALT, D, Enable laptop monitor, exec, hyprctl keyword monitor eDP-1, preferred, auto, 1


# Bind for lazydocker
bindd = SUPER SHIFT CTRL, D, LazyDocker, exec, omarchy-launch-tui lazydocker
# Bind for lazygit
# bindd = SUPER SHIFT CTRL, R, LazyGit, exec, uwsm-app -- lazygit # not working properly for the moment

# Control your input devices --------------------------------------
# See https://wiki.hypr.land/Configuring/Variables/#input
input {
  # Use multiple keyboard layouts and switch between them with Left Alt + Right Alt
  # kb_layout = us,dk,eu
  kb_options = compose:ralt # ,grp:shifts_toggle

  # Change speed of keyboard repeat
  repeat_rate = 40
  repeat_delay = 600

  # Start with numlock on by default
  numlock_by_default = true

  # Increase sensitivity for mouse/trackpad (default: 0)
  # sensitivity = 0.35

  touchpad {
    # Use natural (inverse) scrolling
    natural_scroll = true

    # Use two-finger clicks for right-click instead of lower-right corner
    # clickfinger_behavior = true

    # Control the speed of your scrolling
    scroll_factor = 0.4
  }
}

# Source separated file confs -------------------------------------------------
source = ~/.config/omarchy-supplements/jetbrains.conf
