# Fix all dialogs in Jetbrains products
windowrule {
  name = windowrule-1
  tag = +jb
  match:class = ^jetbrains-.+$
  match:float = 1
}

windowrule {
  name = windowrule-2
  stay_focused = on
  no_initial_focus = on
  match:tag = jb
}

windowrule {
  name = windowrule-3
  focus_on_activate = on
  match:class = ^jetbrains-(?!toolbox)
}

